apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-secret-manager
  namespace: openshift-config
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
