apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-manager-binding
  namespace: aap
  annotations:
  argocd.argoproj.io/hook: PreSync  # Ensures this runs before dependent resources
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: argocd-manager
  apiGroup: rbac.authorization.k8s.io
