# ansible-operator-subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ansible-automation-platform
  namespace: openshift-operators
spec:
  channel: stable-2.3   # Adjust the channel based on your AAP version
  name: ansible-automation-platform
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
