apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ansible-automation-platform-operator
  namespace: aap
  labels:
    operators.coreos.com/ansible-automation-platform-operator.aap: ''
  annotations:
    argocd.argoproj.io/hook: PreSync  # Ensures this runs before dependent resources
spec:
  channel: stable-2.5
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace